// RAG Chat Copilot for Natural Language Application Inquiries

import {
  Bot,
  CheckCircle2,
  FileText,
  HelpCircle,
  Loader2,
  Send,
  Sparkles,
  User
} from 'lucide-react';
import React, { useEffect, useRef, useState } from 'react';
import { useApp } from '../../context/AppContext';
import { Applicant } from '../../types';

interface Props {
  applicant: Applicant;
  onOpenDocument?: (docName: string) => void;
}

export const ChatWithApplication: React.FC<Props> = ({ applicant, onOpenDocument }) => {
  const { chatMessages, sendChatQuery } = useApp();
  const [inputQuery, setInputQuery] = useState('');
  const [isSending, setIsSending] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  const messages = chatMessages[applicant.id] || [];

  const suggestedPrompts = [
    "Summarize this student's profile",
    "What are this student's weaknesses?",
    "Compare transcript and SOP",
    "Does the resume support the SOP?",
    "Would this student fit an MS in AI?",
    "What documents are missing?",
    "Generate 5 tailored interview questions",
    "Audit financial documents for I-20",
    "Generate admission committee summary"
  ];

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages.length, isSending]);

  const handleSend = async (queryToSend?: string) => {
    const text = queryToSend || inputQuery;
    if (!text.trim() || isSending) return;

    setInputQuery('');
    setIsSending(true);

    try {
      await sendChatQuery(applicant.id, text);
    } catch (e) {
      console.error('Chat error:', e);
    } finally {
      setIsSending(false);
    }
  };

  return (
    <div className="flex flex-col h-[650px] bg-white dark:bg-slate-900 rounded-3xl border border-slate-200 dark:border-slate-800 shadow-xl overflow-hidden">
      {/* Chat Header */}
      <div className="flex items-center justify-between px-6 py-4 border-b border-slate-200 dark:border-slate-800 bg-slate-50/50 dark:bg-slate-800/50">
        <div className="flex items-center gap-3">
          <div className="w-9 h-9 rounded-xl bg-gradient-to-tr from-blue-600 to-indigo-600 text-white flex items-center justify-center shadow-md shadow-blue-500/20">
            <Bot className="w-5 h-5" />
          </div>
          <div>
            <h3 className="font-bold text-slate-900 dark:text-white text-sm flex items-center gap-2">
              <span>Chat with Application Dossier</span>
              <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-emerald-100 dark:bg-emerald-950/60 text-emerald-800 dark:text-emerald-300">
                RAG Grounded
              </span>
            </h3>
            <p className="text-[11px] text-slate-500 dark:text-slate-400">
              Querying {applicant.documents.length} verified documents & 7 intelligence agent models for {applicant.firstName} {applicant.lastName}
            </p>
          </div>
        </div>

        <div className="text-right hidden sm:block">
          <span className="text-[10px] font-mono text-slate-400">
            {applicant.targetProgram}
          </span>
        </div>
      </div>

      {/* Message Stream */}
      <div className="flex-1 p-6 overflow-y-auto space-y-6">
        {messages.length === 0 ? (
          <div className="h-full flex flex-col items-center justify-center text-center max-w-lg mx-auto py-8">
            <div className="p-3.5 rounded-2xl bg-blue-50 dark:bg-blue-950/40 text-blue-600 dark:text-blue-400 mb-3 shadow-xs">
              <Sparkles className="w-7 h-7" />
            </div>
            <h4 className="font-bold text-base text-slate-900 dark:text-white">
              Ask Anything About {applicant.firstName}'s Application
            </h4>
            <p className="text-xs text-slate-500 dark:text-slate-400 mt-1 leading-relaxed">
              Every answer is generated by reasoning over actual transcripts, statements of purpose, letters of recommendation, and financial certificates with direct source citations.
            </p>

            {/* Suggested Prompt Pills */}
            <div className="mt-6 flex flex-wrap justify-center gap-2">
              {suggestedPrompts.slice(0, 6).map((prompt, i) => (
                <button
                  key={i}
                  onClick={() => handleSend(prompt)}
                  className="px-3 py-1.5 rounded-xl bg-slate-100 dark:bg-slate-800 hover:bg-blue-50 dark:hover:bg-blue-950/50 hover:text-blue-600 dark:hover:text-blue-400 border border-slate-200 dark:border-slate-700 text-slate-700 dark:text-slate-300 text-xs font-medium transition-all text-left"
                >
                  {prompt} &rarr;
                </button>
              ))}
            </div>
          </div>
        ) : (
          messages.map(msg => {
            const isUser = msg.role === 'USER';
            return (
              <div
                key={msg.id}
                className={`flex gap-3 ${isUser ? 'justify-end' : 'justify-start'}`}
              >
                {!isUser && (
                  <div className="w-8 h-8 rounded-xl bg-indigo-600 text-white flex items-center justify-center shrink-0 mt-1 shadow-xs">
                    <Bot className="w-4 h-4" />
                  </div>
                )}

                <div
                  className={`max-w-2xl rounded-2xl p-4 text-xs leading-relaxed ${
                    isUser
                      ? 'bg-blue-600 text-white rounded-br-none shadow-md shadow-blue-500/20'
                      : 'bg-slate-100/90 dark:bg-slate-800 border border-slate-200/80 dark:border-slate-700 text-slate-800 dark:text-slate-100 rounded-bl-none shadow-xs'
                  }`}
                >
                  {/* Markdown formatted response */}
                  <div className="whitespace-pre-line prose dark:prose-invert prose-xs max-w-none">
                    {msg.content}
                  </div>

                  {/* Citations Card */}
                  {!isUser && msg.citations && msg.citations.length > 0 && (
                    <div className="mt-3.5 pt-3 border-t border-slate-200 dark:border-slate-700 space-y-1.5">
                      <span className="text-[10px] font-bold text-slate-500 dark:text-slate-400 uppercase tracking-wider flex items-center gap-1">
                        <CheckCircle2 className="w-3 h-3 text-emerald-500" />
                        Grounded Sources & Document Citations:
                      </span>
                      <div className="flex flex-wrap gap-1.5">
                        {msg.citations.map((cite, ci) => (
                          <button
                            key={ci}
                            onClick={() => onOpenDocument?.(cite.documentName)}
                            className="inline-flex items-center gap-1 px-2 py-0.5 rounded-md bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 text-[10px] text-blue-600 dark:text-blue-400 font-medium hover:border-blue-500 transition-colors"
                            title={cite.snippet}
                          >
                            <FileText className="w-3 h-3" />
                            <span>{cite.documentName}</span>
                            {cite.pageNumber && <span className="text-slate-400">p.{cite.pageNumber}</span>}
                          </button>
                        ))}
                      </div>
                    </div>
                  )}

                  {/* Follow-up Prompts */}
                  {!isUser && msg.suggestedFollowUps && msg.suggestedFollowUps.length > 0 && (
                    <div className="mt-3 pt-2.5 border-t border-slate-200 dark:border-slate-700 flex flex-wrap items-center gap-1.5">
                      <span className="text-[10px] text-slate-400 flex items-center gap-1">
                        <HelpCircle className="w-3 h-3" />
                        Follow-up:
                      </span>
                      {msg.suggestedFollowUps.map((fu, fi) => (
                        <button
                          key={fi}
                          onClick={() => handleSend(fu)}
                          className="text-[10px] text-blue-600 dark:text-blue-400 hover:underline font-medium"
                        >
                          "{fu}" &bull;
                        </button>
                      ))}
                    </div>
                  )}
                </div>

                {isUser && (
                  <div className="w-8 h-8 rounded-xl bg-blue-100 dark:bg-blue-900/60 text-blue-700 dark:text-blue-300 font-bold flex items-center justify-center shrink-0 mt-1">
                    <User className="w-4 h-4" />
                  </div>
                )}
              </div>
            );
          })
        )}

        {isSending && (
          <div className="flex gap-3 justify-start items-center text-xs text-slate-500">
            <div className="w-8 h-8 rounded-xl bg-indigo-600 text-white flex items-center justify-center shrink-0 animate-pulse">
              <Bot className="w-4 h-4" />
            </div>
            <div className="p-3.5 rounded-2xl bg-slate-100 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 flex items-center gap-2">
              <Loader2 className="w-4 h-4 animate-spin text-blue-600" />
              <span>Retrieving document chunks & reasoning over application profile...</span>
            </div>
          </div>
        )}
        <div ref={messagesEndRef} />
      </div>

      {/* Suggested Quick Prompt Carousel on bottom */}
      {messages.length > 0 && (
        <div className="px-6 py-2 bg-slate-50/80 dark:bg-slate-800/80 border-t border-slate-200 dark:border-slate-800 flex items-center gap-2 overflow-x-auto text-[11px]">
          <span className="text-slate-400 shrink-0 font-medium">Quick Prompts:</span>
          {suggestedPrompts.slice(0, 5).map((p, i) => (
            <button
              key={i}
              onClick={() => handleSend(p)}
              className="shrink-0 px-2.5 py-1 rounded-lg bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 text-slate-700 dark:text-slate-300 hover:border-blue-500 font-medium transition-colors"
            >
              {p}
            </button>
          ))}
        </div>
      )}

      {/* Chat Input Bar */}
      <div className="p-4 border-t border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900">
        <form
          onSubmit={e => {
            e.preventDefault();
            handleSend();
          }}
          className="flex items-center gap-2"
        >
          <input
            type="text"
            placeholder={`Ask any natural language question about ${applicant.firstName}'s credentials, risks, or fit...`}
            value={inputQuery}
            onChange={e => setInputQuery(e.target.value)}
            disabled={isSending}
            className="flex-1 px-4 py-2.5 text-xs rounded-xl border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-800 text-slate-900 dark:text-white placeholder-slate-400 focus:outline-hidden focus:ring-2 focus:ring-blue-500"
          />
          <button
            type="submit"
            disabled={!inputQuery.trim() || isSending}
            className="px-4 py-2.5 rounded-xl bg-blue-600 hover:bg-blue-700 disabled:opacity-50 text-white font-semibold text-xs flex items-center gap-1.5 shadow-xs shadow-blue-500/30 transition-all hover:scale-102 active:scale-98"
          >
            <Send className="w-3.5 h-3.5" />
            <span className="hidden sm:inline">Ask Copilot</span>
          </button>
        </form>
      </div>
    </div>
  );
};
