// Responsible AI Notice Banner

import { AlertTriangle, ShieldCheck } from 'lucide-react';
import React, { useState } from 'react';

export const ResponsibleAIBanner: React.FC = () => {
  const [isExpanded, setIsExpanded] = useState(false);

  return (
    <div className="bg-gradient-to-r from-blue-900 via-indigo-900 to-slate-900 text-white text-xs px-4 py-2 border-b border-indigo-700/50 shadow-sm print:hidden">
      <div className="max-w-7xl mx-auto flex flex-wrap items-center justify-between gap-2">
        <div className="flex items-center gap-2">
          <span className="flex items-center justify-center p-1 rounded-full bg-blue-500/20 text-blue-300">
            <ShieldCheck className="w-3.5 h-3.5" />
          </span>
          <span className="font-semibold text-blue-200 uppercase tracking-wider text-[10px]">Responsible AI Notice:</span>
          <span className="text-slate-200">
            This recommendation is generated by AI to assist admissions officers. Final admission decisions must always be made by authorized university staff.
          </span>
        </div>

        <button
          onClick={() => setIsExpanded(!isExpanded)}
          className="text-blue-300 hover:text-white underline text-[11px] font-medium transition-colors ml-auto"
        >
          {isExpanded ? 'Hide Governance Details' : 'Governance & Policy Info'}
        </button>
      </div>

      {isExpanded && (
        <div className="max-w-7xl mx-auto mt-2 pt-2 border-t border-indigo-700/40 text-[11px] text-slate-300 grid grid-cols-1 md:grid-cols-3 gap-3">
          <div className="flex items-start gap-1.5">
            <AlertTriangle className="w-3.5 h-3.5 text-amber-400 shrink-0 mt-0.5" />
            <p><strong>Non-Autonomous System:</strong> The AI acts strictly as an evidence-retrieval and comparative copilot. Automated rejection or acceptance is prohibited.</p>
          </div>
          <div className="flex items-start gap-1.5">
            <ShieldCheck className="w-3.5 h-3.5 text-emerald-400 shrink-0 mt-0.5" />
            <p><strong>Evidence Grounding:</strong> Every score and claim is cross-referenced with submitted PDF/DOCX/scanned documents with traceable citations.</p>
          </div>
          <div className="flex items-start gap-1.5">
            <ShieldCheck className="w-3.5 h-3.5 text-indigo-400 shrink-0 mt-0.5" />
            <p><strong>Human Decision Authority:</strong> Final admissions offers, conditions, and visa eligibility are locked only upon human officer sign-off.</p>
          </div>
        </div>
      )}
    </div>
  );
};
