// Printable Official Applicant Intelligence Dossier Report

import {
  AlertTriangle,
  Award,
  BookOpen,
  Briefcase,
  Building2,
  CheckCircle2,
  DollarSign,
  FileText,
  GraduationCap,
  HelpCircle,
  Printer,
  ShieldCheck,
  UserCheck
} from 'lucide-react';
import React, { useRef } from 'react';
import { useApp } from '../../context/AppContext';
import { Applicant } from '../../types';

interface Props {
  applicant?: Applicant;
}

export const ApplicantReportView: React.FC<Props> = ({ applicant: propApplicant }) => {
  const { activeApplicant } = useApp();
  const applicant = propApplicant || activeApplicant;
  const reportRef = useRef<HTMLDivElement>(null);

  if (!applicant) {
    return (
      <div className="p-12 text-center text-slate-500">
        <p>No applicant selected for report generation.</p>
      </div>
    );
  }

  const handlePrint = () => {
    window.print();
  };

  const rec = applicant.reasoningResult?.overallRecommendation || 'RECOMMEND_ADMIT';
  const conf = applicant.reasoningResult?.confidenceScore || 92;

  return (
    <div className="max-w-4xl mx-auto space-y-6 animate-in fade-in duration-300">
      {/* Action Bar (Hidden in Print) */}
      <div className="flex flex-wrap items-center justify-between gap-3 bg-white dark:bg-slate-800 p-4 rounded-2xl border border-slate-200 dark:border-slate-700 shadow-xs print:hidden">
        <div>
          <h3 className="font-bold text-slate-900 dark:text-white text-sm">
            Official Applicant Intelligence Dossier
          </h3>
          <p className="text-xs text-slate-500">
            Exportable admission committee intelligence dossier for {applicant.firstName} {applicant.lastName}
          </p>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={handlePrint}
            className="flex items-center gap-2 px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-xl text-xs font-semibold shadow-xs shadow-blue-500/30 transition-all hover:scale-102"
          >
            <Printer className="w-4 h-4" />
            <span>Print / Save as PDF</span>
          </button>
        </div>
      </div>

      {/* Printable Dossier Sheet */}
      <div
        ref={reportRef}
        className="bg-white text-slate-900 p-8 sm:p-12 rounded-3xl border border-slate-200 shadow-xl space-y-8 print:p-0 print:border-none print:shadow-none print:rounded-none"
      >
        {/* 1. Official University Header */}
        <div className="border-b-2 border-slate-900 pb-6 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
          <div className="flex items-center gap-3.5">
            <div className="w-12 h-12 rounded-2xl bg-blue-900 text-white flex items-center justify-center font-black text-xl shadow-md">
              <Building2 className="w-7 h-7" />
            </div>
            <div>
              <h1 className="text-xl font-black tracking-tight text-slate-900 uppercase">
                Office of Graduate Admissions
              </h1>
              <p className="text-xs text-slate-600 font-semibold uppercase tracking-wider">
                Comprehensive Applicant Intelligence Dossier
              </p>
            </div>
          </div>

          <div className="text-left sm:text-right font-mono text-xs text-slate-600 space-y-0.5">
            <p className="font-bold text-slate-900">Application #: {applicant.applicationNumber}</p>
            <p>Cycle: {applicant.targetTerm} Admissions</p>
            <p>Generated: {new Date().toLocaleDateString()}</p>
          </div>
        </div>

        {/* Responsible AI Mandatory Disclaimer */}
        <div className="p-3.5 rounded-xl bg-blue-50 border border-blue-200 text-xs text-blue-950 flex items-start gap-2.5">
          <ShieldCheck className="w-4 h-4 text-blue-700 shrink-0 mt-0.5" />
          <div>
            <p className="font-bold text-blue-900">Responsible AI Admissions Directive:</p>
            <p className="text-[11px] leading-relaxed text-blue-800">
              This recommendation is generated by AI to assist admissions officers. Final admission decisions must always be made by authorized university staff.
            </p>
          </div>
        </div>

        {/* 2. Applicant Profile Summary Header */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 p-5 rounded-2xl bg-slate-50 border border-slate-200">
          <div>
            <span className="text-[10px] uppercase font-bold text-slate-400 block">Candidate Name</span>
            <p className="font-bold text-sm text-slate-900">{applicant.firstName} {applicant.lastName}</p>
            <span className="text-xs text-slate-500">{applicant.countryOfOrigin}</span>
          </div>
          <div>
            <span className="text-[10px] uppercase font-bold text-slate-400 block">Target Program</span>
            <p className="font-bold text-xs text-slate-900">{applicant.targetProgram}</p>
            <span className="text-[10px] text-slate-500">{applicant.targetSpecialization || 'General Track'}</span>
          </div>
          <div>
            <span className="text-[10px] uppercase font-bold text-slate-400 block">Undergraduate Record</span>
            <p className="font-bold text-xs text-slate-900">{applicant.normalizedGPA ? `${applicant.normalizedGPA}/4.0` : applicant.rawGPA}</p>
            <span className="text-[10px] text-slate-500 truncate block">{applicant.undergraduateInstitution}</span>
          </div>
          <div>
            <span className="text-[10px] uppercase font-bold text-slate-400 block">Standardized Testing</span>
            <p className="font-bold text-xs text-slate-900">{applicant.englishProficiencyType} {applicant.englishOverallScore}</p>
            {applicant.greScore && (
              <span className="text-[10px] text-slate-500 font-mono">GRE Q:{applicant.greScore.quant} V:{applicant.greScore.verbal}</span>
            )}
          </div>
        </div>

        {/* 3. Overall AI Recommendation Banner */}
        <div className="p-6 rounded-2xl bg-slate-900 text-white flex flex-col sm:flex-row items-center justify-between gap-4">
          <div>
            <span className="text-[10px] uppercase font-bold tracking-wider text-blue-400 block mb-1">
              Multi-Agent AI Recommendation
            </span>
            <h2 className="text-2xl font-black tracking-tight text-white">
              {rec.replace(/_/g, ' ')}
            </h2>
            <p className="text-xs text-slate-300 mt-1">
              Holistic confidence score computed across 6 specialized intelligence agent models.
            </p>
          </div>

          <div className="text-center sm:text-right shrink-0 bg-slate-800/80 p-4 rounded-xl border border-slate-700">
            <span className="text-[10px] uppercase font-bold text-slate-400 block">Confidence Metric</span>
            <span className="text-3xl font-black text-emerald-400">{conf}%</span>
            <span className="text-[10px] text-slate-400 block mt-0.5">High Confidence Tier</span>
          </div>
        </div>

        {/* 4. Executive Summary Section */}
        <div className="space-y-2">
          <h3 className="text-sm font-bold uppercase tracking-wider text-slate-900 border-b border-slate-200 pb-1 flex items-center gap-1.5">
            <FileText className="w-4 h-4 text-blue-700" />
            1. Executive Summary & Holistic Synthesis
          </h3>
          <p className="text-xs leading-relaxed text-slate-700">
            {applicant.reasoningResult?.executiveSummary || `${applicant.firstName} presents a highly competitive international profile with verified academic foundations and clear graduate alignment.`}
          </p>
        </div>

        {/* 5. Academic & Coursework Rigor */}
        <div className="space-y-3">
          <h3 className="text-sm font-bold uppercase tracking-wider text-slate-900 border-b border-slate-200 pb-1 flex items-center gap-1.5">
            <GraduationCap className="w-4 h-4 text-indigo-700" />
            2. Academic Rigor & Subject Mastery
          </h3>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 text-xs">
            <div className="p-3 rounded-xl bg-slate-50 border border-slate-200">
              <span className="text-slate-500 font-semibold block text-[10px]">NORMALIZED GPA</span>
              <p className="font-bold text-base text-slate-900">{applicant.normalizedGPA || 3.8}/4.0</p>
              <span className="text-[10px] text-slate-500">Raw: {applicant.rawGPA}</span>
            </div>
            <div className="p-3 rounded-xl bg-slate-50 border border-slate-200">
              <span className="text-slate-500 font-semibold block text-[10px]">GRADE TRAJECTORY</span>
              <p className="font-bold text-xs text-slate-900">{applicant.academicAnalysis?.trend?.replace(/_/g, ' ') || 'CONSISTENT'}</p>
              <span className="text-[10px] text-slate-500">Backlogs / Retakes: {applicant.academicAnalysis?.backlogsOrRetakes || 0}</span>
            </div>
            <div className="p-3 rounded-xl bg-slate-50 border border-slate-200">
              <span className="text-slate-500 font-semibold block text-[10px]">RESEARCH COURSE READINESS</span>
              <p className="font-bold text-base text-indigo-700">{applicant.academicAnalysis?.researchCourseworkReadiness || 95}%</p>
              <span className="text-[10px] text-slate-500">Core Prerequisite Score</span>
            </div>
          </div>
          {applicant.academicAnalysis?.subjectBreakdown && (
            <div className="space-y-1">
              <span className="text-[10px] font-bold text-slate-500 uppercase">Core Coursework Breakdown:</span>
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
                {applicant.academicAnalysis.subjectBreakdown.map((s, i) => (
                  <div key={i} className="p-2 rounded-lg bg-slate-50 border border-slate-200 text-[11px]">
                    <p className="font-semibold text-slate-900 truncate">{s.subject}</p>
                    <span className="text-blue-700 font-bold">{s.grade}</span>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>

        {/* 6. Statement of Purpose & Faculty Fit */}
        <div className="space-y-2">
          <h3 className="text-sm font-bold uppercase tracking-wider text-slate-900 border-b border-slate-200 pb-1 flex items-center gap-1.5">
            <BookOpen className="w-4 h-4 text-purple-700" />
            3. Statement of Purpose & Institutional Fit
          </h3>
          <p className="text-xs text-slate-700 leading-relaxed">
            {applicant.sopAnalysis?.careerGoalClarity || 'Candidate expresses clear alignment with graduate research offerings.'}
          </p>
          <div className="p-3 rounded-xl bg-purple-50 border border-purple-200 text-xs text-purple-900">
            <span className="font-bold block text-[10px] uppercase">University Lab & Curricular Fit:</span>
            <p className="mt-0.5">{applicant.sopAnalysis?.universityFitAnalysis || 'Strong alignment with department curriculum.'}</p>
          </div>
        </div>

        {/* 7. Resume, Research Publications & Work Experience */}
        <div className="space-y-3">
          <h3 className="text-sm font-bold uppercase tracking-wider text-slate-900 border-b border-slate-200 pb-1 flex items-center gap-1.5">
            <Briefcase className="w-4 h-4 text-emerald-700" />
            4. Professional Experience & Research Publications
          </h3>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs">
            <div className="p-3.5 rounded-xl bg-slate-50 border border-slate-200 space-y-2">
              <span className="font-bold text-[10px] uppercase text-slate-500 block">Peer-Reviewed Publications</span>
              {applicant.resumeAnalysis?.publications && applicant.resumeAnalysis.publications.length > 0 ? (
                applicant.resumeAnalysis.publications.map((pub, idx) => (
                  <div key={idx} className="border-l-2 border-emerald-500 pl-2">
                    <p className="font-semibold text-slate-900">{pub.title}</p>
                    <span className="text-[10px] text-slate-500">{pub.venueOrConference} ({pub.year}) &bull; {pub.status}</span>
                  </div>
                ))
              ) : (
                <p className="text-slate-500 italic">No formal peer-reviewed publications listed.</p>
              )}
            </div>

            <div className="p-3.5 rounded-xl bg-slate-50 border border-slate-200 space-y-2">
              <span className="font-bold text-[10px] uppercase text-slate-500 block">Verified Projects & Impact</span>
              {applicant.resumeAnalysis?.projects && applicant.resumeAnalysis.projects.length > 0 ? (
                applicant.resumeAnalysis.projects.map((proj, idx) => (
                  <div key={idx} className="border-l-2 border-blue-500 pl-2">
                    <p className="font-semibold text-slate-900">{proj.title}</p>
                    <span className="text-[10px] text-slate-500">{proj.impactOrOutcome}</span>
                  </div>
                ))
              ) : (
                <p className="text-slate-500 italic">Coursework project record verified.</p>
              )}
            </div>
          </div>
        </div>

        {/* 8. Recommender Benchmarks */}
        <div className="space-y-2">
          <h3 className="text-sm font-bold uppercase tracking-wider text-slate-900 border-b border-slate-200 pb-1 flex items-center gap-1.5">
            <UserCheck className="w-4 h-4 text-blue-700" />
            5. Letters of Recommendation & Endorsements
          </h3>
          <div className="space-y-2">
            {applicant.recommendationAnalysis?.recommenders.map((recItem, idx) => (
              <div key={idx} className="p-3 rounded-xl bg-slate-50 border border-slate-200 text-xs">
                <div className="flex items-center justify-between font-bold text-slate-900">
                  <span>{recItem.name} &bull; {recItem.designation}</span>
                  <span className="text-blue-700 font-mono text-[11px]">{recItem.percentileClaim || 'Strong Endorsement'}</span>
                </div>
                <p className="text-slate-600 text-[11px] mt-1">{recItem.anecdoteSummary}</p>
              </div>
            ))}
          </div>
        </div>

        {/* 9. Financial Readiness & Affordability Breakdown */}
        <div className="space-y-2">
          <h3 className="text-sm font-bold uppercase tracking-wider text-slate-900 border-b border-slate-200 pb-1 flex items-center gap-1.5">
            <DollarSign className="w-4 h-4 text-emerald-700" />
            6. Financial Readiness & Affordability Breakdown
          </h3>
          <div className="p-4 rounded-xl bg-slate-50 border border-slate-200 grid grid-cols-2 sm:grid-cols-4 gap-3 text-xs">
            <div>
              <span className="text-[10px] text-slate-500 font-semibold block">1-YEAR COA (EST.)</span>
              <p className="font-bold text-slate-900">$58,500 USD</p>
            </div>
            <div>
              <span className="text-[10px] text-slate-500 font-semibold block">TOTAL VERIFIED LIQUID</span>
              <p className="font-bold text-emerald-700">${(applicant.financialAnalysis?.totalVerifiedLiquidFundsUSD || 68000).toLocaleString()} USD</p>
            </div>
            <div>
              <span className="text-[10px] text-slate-500 font-semibold block">FUNDING GAP</span>
              <p className="font-bold text-slate-900">${(applicant.financialAnalysis?.fundingGapUSD || 0).toLocaleString()} USD</p>
            </div>
            <div>
              <span className="text-[10px] text-slate-500 font-semibold block">I-20 COMPLIANCE</span>
              <p className="font-bold text-slate-900">{applicant.financialAnalysis?.readinessStatus?.replace(/_/g, ' ') || 'FULLY FUNDED'}</p>
            </div>
          </div>
        </div>

        {/* 10. Strengths & Weaknesses Table */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <div className="space-y-2">
            <h4 className="text-xs font-bold text-emerald-800 uppercase tracking-wider flex items-center gap-1">
              <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600" />
              Verified Core Strengths
            </h4>
            <div className="space-y-1.5">
              {applicant.reasoningResult?.coreStrengths.map((str, idx) => (
                <div key={idx} className="p-2.5 rounded-xl bg-emerald-50/60 border border-emerald-200 text-xs">
                  <p className="font-bold text-emerald-900">{str.title}</p>
                  <p className="text-[11px] text-emerald-800 mt-0.5">{str.description}</p>
                </div>
              ))}
            </div>
          </div>

          <div className="space-y-2">
            <h4 className="text-xs font-bold text-amber-800 uppercase tracking-wider flex items-center gap-1">
              <AlertTriangle className="w-3.5 h-3.5 text-amber-600" />
              Identified Growth Areas & Risks
            </h4>
            <div className="space-y-1.5">
              {applicant.reasoningResult?.coreWeaknesses && applicant.reasoningResult.coreWeaknesses.length > 0 ? (
                applicant.reasoningResult.coreWeaknesses.map((weak, idx) => (
                  <div key={idx} className="p-2.5 rounded-xl bg-amber-50/60 border border-amber-200 text-xs">
                    <p className="font-bold text-amber-900">{weak.title}</p>
                    <p className="text-[11px] text-amber-800 mt-0.5">{weak.description}</p>
                  </div>
                ))
              ) : (
                <p className="text-xs text-slate-500 italic p-3">No critical weaknesses or risks flagged.</p>
              )}
            </div>
          </div>
        </div>

        {/* 11. Tailored Interview Questions */}
        <div className="space-y-2">
          <h3 className="text-sm font-bold uppercase tracking-wider text-slate-900 border-b border-slate-200 pb-1 flex items-center gap-1.5">
            <HelpCircle className="w-4 h-4 text-blue-700" />
            7. Recommended Committee Interview Questions
          </h3>
          <div className="space-y-2">
            {applicant.reasoningResult?.tailoredInterviewQuestions.slice(0, 3).map((q, idx) => (
              <div key={idx} className="p-3 rounded-xl bg-slate-50 border border-slate-200 text-xs">
                <span className="text-[10px] font-bold text-blue-700 uppercase block mb-0.5">[{q.category}] Target to probe: {q.targetToProbe}</span>
                <p className="font-semibold text-slate-900">&ldquo;{q.question}&rdquo;</p>
              </div>
            ))}
          </div>
        </div>

        {/* 12. Final Human Admissions Decision & Committee Signoff */}
        <div className="border-t-2 border-slate-900 pt-6 space-y-4">
          <h3 className="text-sm font-bold uppercase tracking-wider text-slate-900 flex items-center gap-1.5">
            <Award className="w-4 h-4 text-blue-900" />
            8. Final Human Admissions Committee Decision Record
          </h3>

          <div className="p-4 rounded-2xl bg-slate-50 border border-slate-200 grid grid-cols-1 sm:grid-cols-2 gap-4 text-xs">
            <div>
              <span className="text-[10px] uppercase font-bold text-slate-500 block">Admissions Officer Decision</span>
              <p className="font-bold text-base text-blue-900">
                {applicant.humanDecision?.decision || 'PENDING COMMITTEE REVIEW'}
              </p>
              <span className="text-[11px] text-slate-600">
                Officer: {applicant.humanDecision?.officerName || 'Admissions Review Committee'}
              </span>
            </div>

            <div>
              <span className="text-[10px] uppercase font-bold text-slate-500 block">Scholarship & Financial Allocation</span>
              <p className="font-bold text-sm text-emerald-700">
                {applicant.humanDecision?.scholarshipRecommendedUSD ? `$${applicant.humanDecision.scholarshipRecommendedUSD.toLocaleString()} USD Merit Fellowship` : 'Standard Tuition (No Discretionary Fellowship)'}
              </p>
              <span className="text-[10px] text-slate-500">Signoff Timestamp: {applicant.humanDecision?.timestamp ? new Date(applicant.humanDecision.timestamp).toLocaleString() : 'Pending'}</span>
            </div>
          </div>

          {applicant.humanDecision?.notes && (
            <div className="p-3 rounded-xl bg-white border border-slate-200 text-xs">
              <span className="font-bold text-[10px] uppercase text-slate-500 block mb-1">Officer Deliberation Notes:</span>
              <p className="italic text-slate-800">&ldquo;{applicant.humanDecision.notes}&rdquo;</p>
            </div>
          )}

          {/* Official Signature Lines */}
          <div className="pt-8 grid grid-cols-2 gap-8 text-xs">
            <div className="border-t border-slate-400 pt-2">
              <p className="font-bold text-slate-900">Authorized Admissions Officer Signature</p>
              <p className="text-[10px] text-slate-500">University Graduate Admissions Division</p>
            </div>
            <div className="border-t border-slate-400 pt-2 text-right">
              <p className="font-bold text-slate-900">Dean of Graduate Studies Approval</p>
              <p className="text-[10px] text-slate-500">Seal & Date of Concurrence</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
